package com.example.api;

/**
 * Created by szymon on 21.04.16.
 */
public enum ApiResponseStatus {

    SUCCESS,VALIDATION_ERROR, INTERNAL_SERVER_ERROR, CONFIGURATION_NOT_SUPORTED, AUTHENTICATION_FAUILURE, TOKEN_EXPIRED, WRONG_TOKEN, TOKEN_NOT_FOUND;
}
